model_state:
  # Publish all joint states -----------------------------------
  # joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50  

  #position controllers --------------------------------
model_control:
  type: position_controllers/JointGroupPositionController
  joints:
    - rev_1
    - slide_left
    - slide_right
    
 
 
 
 
 
  # Effort Controllers ---------------------------------------
joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: rev_1
    pid: {p: 50.0, i: 0.01, d: 30.0}

joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: slide_left
    pid: {p: 50.0, i: 0.01, d: 30.0}

joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: slide_right
    pid: {p: 50.0, i: 0.01, d: 30.0}